server:
  port: 8724
  
spring:
  application: 
    name: monitor-hystrix-server
  security:
    user:
      name: 'admin'
      password: 'admin'
  boot:
      admin:
        client:
          url: http://localhost:8723
          instance:
              service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  cloud: 
    config: 
      discovery: 
        enabled: true
        service-id: config-server
      profile: dev
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8730/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
       user.name: ${spring.security.user.name}
       user.password: ${spring.security.user.password}
  server:
    enable-self-preservation: false 

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS   

turbine:
  app-config: auth-server,config-server,system-server,gateway-server    ##需要监控的服务名
  aggregator:
    clusterConfig: default    ##需要监控的服务集群名
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
  combine-host-port: true 