server:
  port: 8727
  
spring:
  application: 
    name: auth-server
  boot:
      admin:
        client:
          url: http://localhost:8723
          instance:
            service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  cloud: 
    config: 
      discovery: 
        enabled: true
        service-id: config-server
      profile: dev
      label: master
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8730/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS    

mybatis-plus:
  mapper-locations: org/arain/**/mapper/*Mapper.xml
  typeAliasesPackage: org.arain.spring.common.**.entity
