#server start
server:
  port: 8987
#server end

spring:
  application:
    name: config-server
  boot:
      admin:
        client:
          url: http://localhost:8723
          instance:
            service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/
  profiles:
    active:
    - native
#        git:
#          uri: https://github.com/rain10/spring/
#          search-paths:
#          - spring-config
#          username: rain1026
#          password: dy18011447905
#          force-pull: true
  rabbitmq:
       host: 127.0.0.1
       port: 5672
       username: admin
       password: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8730/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
