#server start
server:
  port: 8888
#server end

spring:
  application:
    name: config-server
  boot:
      admin:
        client:
          url: http://localhost:8723
          instance:
            service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/
  profiles:
    active:
    - native

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8730/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
