server:
  port: 8723
  
spring:
  application: 
    name: monitor-admin-server
  security:
    user:
      name: 'admin'
      password: 'admin'
  cloud: 
    config: 
      discovery: 
        enabled: true
        service-id: config-server
      profile: dev
      label: master
  mail:
    host: smtp.qq.com
    username: 2530728915@qq.com
    password: 
    properties:
      mail.debug: false  
      mail.smtp.auth: true  
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8730/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
       user.name: ${spring.security.user.name}
       user.password: ${spring.security.user.password}
  server:
    enable-self-preservation: false 
   
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS     
