server:
  port: 8722
  
spring:
  application: 
    name: system-server
#  boot:
#      admin:
#        client:
#          url: http://localhost:8723
#          instance:
#            service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  cloud: 
    config: 
      discovery: 
        enabled: true
        service-id: config-server
      profile: dev
      label: master


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8730/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: false  
    
# 必须配置
feign:
  hystrix:
    enabled: true#开启Feign Hystrix 支持